//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkhMorporkMVC.GameLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Events {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Events() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnkhMorporkMVC.GameLogic.Resources.Events", typeof(Events).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The gang beated you to death with tea bags...
        ///.
        /// </summary>
        internal static string AssasinEventFail {
            get {
                return ResourceManager.GetString("AssasinEventFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Unfriendly people didn&apos;t like the reward you offered. 
        ///.
        /// </summary>
        internal static string AssassinEventRewardGuessedWrong {
            get {
                return ResourceManager.GetString("AssassinEventRewardGuessedWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Say your reward!(You have only 1 try to guess)
        ///.
        /// </summary>
        internal static string AssassinEventRewardGuessWelcome {
            get {
                return ResourceManager.GetString("AssassinEventRewardGuessWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///You were lucky - assasins took the bribe
        ///and disappeared in the dark.
        ///.
        /// </summary>
        internal static string AssassinEventSuccess {
            get {
                return ResourceManager.GetString("AssassinEventSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///You bumped into a gang of Assasins! They say someone set a contract to kill you. But we can have a deal Show us your pocket, and if someone likes it&apos;s content and 
        ///has a free time to help you eliminate your assination orderer, we&apos;re good.
        ///Accept the offer? (Enter &apos;Yes&apos; or &apos;No&apos;)
        ///.
        /// </summary>
        internal static string AssassinEventWelcome {
            get {
                return ResourceManager.GetString("AssassinEventWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Wrong input, please enter your reward (positive number)!
        ///.
        /// </summary>
        internal static string AssassinEventWrongReward {
            get {
                return ResourceManager.GetString("AssassinEventWrongReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///A random beggar named {0} ({1}) has been disturbing you for more than an hour already. It looks like if you don&apos;t give him a bottle of beer, he will chase you to death Give alms to {2}? (Enter &apos;Yes&apos; or &apos;No&apos;)
        ///.
        /// </summary>
        internal static string BeerBeggarWelcome {
            get {
                return ResourceManager.GetString("BeerBeggarWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{0} saw you&apos;re short on money.
        ///.
        /// </summary>
        internal static string BeggarEventFail {
            get {
                return ResourceManager.GetString("BeggarEventFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Beggar and his mates chased you on your way until you found your death...
        ///.
        /// </summary>
        internal static string BeggarEventNotEnoughMoney {
            get {
                return ResourceManager.GetString("BeggarEventNotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{0} got his coins and went away.
        ///.
        /// </summary>
        internal static string BeggarEventSuccess {
            get {
                return ResourceManager.GetString("BeggarEventSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///A random beggar named {0} ({1}) has been disturbing you for more than an hour already. It looks like if you don&apos;t give him alms ( {2} ), he will chase you to death
        ///Give alms to {3}? (Enter &apos;Yes&apos; or &apos;No&apos;)
        ///.
        /// </summary>
        internal static string BeggarEventWelcome {
            get {
                return ResourceManager.GetString("BeggarEventWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///You had no beer, so beggar mumbled you to death..
        ///.
        /// </summary>
        internal static string BeggarNoBeer {
            get {
                return ResourceManager.GetString("BeggarNoBeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{0} said that it will be sad for him to joke around alone today and left.
        ///.
        /// </summary>
        internal static string FoolEventFail {
            get {
                return ResourceManager.GetString("FoolEventFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///You had a great time fooling around and earn some money!
        ///.
        /// </summary>
        internal static string FoolEventSuccess {
            get {
                return ResourceManager.GetString("FoolEventSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///You met your highschool homie, {0} ({1}) He offers you to join him and earn some money ( {2} ) Wanna join him? (Enter &apos;Yes&apos; or &apos;No&apos;)
        ///.
        /// </summary>
        internal static string FoolEventWelcome {
            get {
                return ResourceManager.GetString("FoolEventWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///You&apos;re passing by the Mended Drum pub. They sell beer there for {0} per bottle. Enter and buy a beer? (Enter &apos;Yes&apos; or &apos;No&apos; )
        ///.
        /// </summary>
        internal static string MendedDrumWelcome {
            get {
                return ResourceManager.GetString("MendedDrumWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///You&apos;ve bought a bottle of beer!
        ///.
        /// </summary>
        internal static string PubInteractionSuccesfull {
            get {
                return ResourceManager.GetString("PubInteractionSuccesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///You&apos;re short on money, so no beer for you!
        ///.
        /// </summary>
        internal static string PubNotEnoughMoney {
            get {
                return ResourceManager.GetString("PubNotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Unfortunately, the pub is closed.
        ///.
        /// </summary>
        internal static string PubWasClosed {
            get {
                return ResourceManager.GetString("PubWasClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///You were killed by {0}.
        ///.
        /// </summary>
        internal static string ThieveEventFail {
            get {
                return ResourceManager.GetString("ThieveEventFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///There was not enough money to save your life..
        ///.
        /// </summary>
        internal static string ThieveEventNotEnoughMoney {
            get {
                return ResourceManager.GetString("ThieveEventNotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Thieve {0} spared your life today.
        ///.
        /// </summary>
        internal static string ThieveEventSuccess {
            get {
                return ResourceManager.GetString("ThieveEventSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///There&apos;s a thieve {0} on the way and your back is against the wall. Thieve&apos;s demand is {1}. Your only way to survive is to pay off... Give the money? (Enter &apos;Yes&apos; or &apos;No&apos;)
        ///.
        /// </summary>
        internal static string ThieveEventWelcome {
            get {
                return ResourceManager.GetString("ThieveEventWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thieve has released you, cause there are too much thefts in this city...
        /// </summary>
        internal static string ThieveTooMuchThefts {
            get {
                return ResourceManager.GetString("ThieveTooMuchThefts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Your hands are busy, you can&apos;t buy a beer.
        ///.
        /// </summary>
        internal static string TooMuchBeer {
            get {
                return ResourceManager.GetString("TooMuchBeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stranger.
        /// </summary>
        internal static string UnknownEntityName {
            get {
                return ResourceManager.GetString("UnknownEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Pocket: {0}; Beers: {1} bottle(s).
        ///
        ///.
        /// </summary>
        internal static string UserBalanceOutput {
            get {
                return ResourceManager.GetString("UserBalanceOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Input is not valid, please anter &apos;{0}&apos; or &apos;{1}&apos;!
        ///.
        /// </summary>
        internal static string UserInputNotValid {
            get {
                return ResourceManager.GetString("UserInputNotValid", resourceCulture);
            }
        }
    }
}
